[package]
name = "task_management_api"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres", "derive", "uuid", "chrono" ] }

[dependencies.axum]
version = "0.8.1"
