CREATE TABLE IF NOT EXISTS boards (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    user_id UUID NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);